#!/bin/bash

## Terminal - powerline setting
#if [ -f ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh ]; then
#  source ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
#fi

HOST_NAME=$(hostname)
UNAME=$(uname)
#ROS_DISTRO=melodic
#ROS_DISTRO=noetic

# OSX
if [ "$UNAME" = "Darwin" ];then
  BASE_DIR="$HOME/SynologyDrive"
else
# Linux
  CODE_NAME=$(lsb_release -c -s)
  # Post Common Sourcing File
  if [ "$HOST_NAME" = "tegra-ubuntu" ];then
    BASE_DIR="$HOME"
  elif [ "$HOST_NAME" = "linuxkit-025000000001" ];then
    BASE_DIR="$HOME"
  elif [ "$HOST_NAME" = "ubuntu" ];then
    BASE_DIR="/mnt/hgfs/SynologyDrive"
  elif [ "$HOST_NAME" = "drcl-Jxavier" ];then
    BASE_DIR="$HOME/ShareData_SSD"
  elif [ "$HOST_NAME" = "cdi-VM" ];then
    BASE_DIR="$HOME"
    WS_DIR="$BASE_DIR/workspace"
  elif [ "$HOST_NAME" = "cdi-ZBook" ];then
    BASE_DIR="$HOME/DRCL\ Dropbox/Workspace_CDI"
    WS_DIR="$BASE_DIR/workspace_prog"
    ROS_DISTRO=noetic
  else
    BASE_DIR="$HOME/DRCL\ Dropbox/Workspace_CDI"
    WS_DIR="$BASE_DIR/workspace_prog"
    #ROS_DISTRO=noetic
  fi
fi

#WS_DIR="$BASE_DIR/workspace_prog"
#CATKIN_DIR="$BASE_DIR/workspace_prog/catkin_ws"
CATKIN_WS_GIT="https://dongilc:DRCLy121@github.com/dongilc/catkin_ws.git"
BASH_GIT="https://dongilc:DRCLy121@github.com/dongilc/bash.git"
VESC_FW_GIT="https://dongilc:DRCLy121@github.com/dongilc/bldc_5.02_openrobot_ver1.git"

## ROS
#ROS_CONN_DEVICE="wlp59s0" # wlp59s0, wlan0, eth0
#ROS_MASTER_IP=$(ifconfig $ROS_CONN_DEVICE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
#ROS_HOST_IP="192.168.27.?" #
if [ "$UNAME" = "Darwin" ];then
  GIT_NOW=$(date)[$HOST_NAME]
else
  GIT_NOW=$(date '+%D(%T)' -d 'now')[$HOST_NAME]
fi
# ROS Configuration
#export ROS_MASTER_URI="http://192.168.28.102:11311"
#export ROS_HOSTNAME="192.168.28.102"
#if [ "$UNAME" = "Linux" ];then
#  source $CATKIN_DIR/devel/setup.bash
#fi

# Frequent Commands, CDI for system control
alias off='sudo shutdown -h now' #requires root password, disable it by "sudo chmod u+s /sbin/shutdown"
alias rb='sudo shutdown -r now' #requires root password, disable it by "sudo chmod u+s /sbin/shutdown"
alias susp='sudo pm-suspend'
alias lschm='stat -c '"'"'%a %n'"'"' *'
alias up='sudo apt update && sudo apt upgrade'
alias ss='service --status-all | grep +'

# Frequent Commands. CDI - Connections
alias lrs='export ROS_MASTER_URI=http://localhost:11311'
alias csr='ssh -Y cdi@192.168.28.72'
alias csj='ssh -Y nvidia@192.168.28.5'
alias amg='ssh -Y nvidia@192.168.28.121'
alias ras='ssh -Y pi@192.168.28.32'
alias hqr='ssh -Y nvidia@192.168.1.10'

# Set ROS Alias Commands
alias cw="cd $WS_DIR"
alias cc="cd $CATKIN_DIR"
alias cs="cd $WS_DIR/catkin_ws/src"
alias cb="cd $WS_DIR/bash"
alias cg="cd $WS_DIR/github_ws"
alias ck="cd $WS_DIR/docker_ws"
alias cf="cd $WS_DIR/vescuino_fw/bldc_5.02_openrobot_ver3"
alias cm='catkin_make'
alias rc='rm -rf ./build ./devel'
alias rd='rosdep install --from-paths . --ignore-src -r -y'
alias vt='~/vesc_tool_0.95'
alias ml='~/MATLAB/R2016b/bin/matlab'
alias sd='source devel/setup.bash'
alias rp='rospack profile'
alias rv='roslaunch vesc_driver vesc_driver_node.launch port:=/dev/ttyACM0'
alias rv1='roslaunch vesc_driver vesc_driver_node.launch port:=/dev/ttyACM1'
alias dr='roslaunch diff_wheel_platform diff_wheel_platform_teleop.launch'
alias am='roslaunch amg_p1 amg_p1_teleop.launch'
alias vc='roslaunch vesc_control_ex1 vesc_control_ex1_teleop.launch'
alias vc1='roslaunch vesc_control_ex1 vesc_control_ex1_teleop.launch'
alias vc2='roslaunch vesc_control_ex2 vesc_control_ex2_teleop.launch'
alias vc3='roslaunch vesc_control_ex3 vesc_control_ex3_teleop.launch'
alias vc4='roslaunch vesc_control_ex4 vesc_control_ex4_teleop.launch'
alias or='roslaunch omniwheel_robot omniwheel_robot_teleop.launch port:=/dev/ttyACM1'
alias ki='rosrun teleop_twist_keyboard teleop_twist_keyboard.py'
alias hqvrep='roslaunch huboq_teleop huboq_teleop.launch'
alias hq='roslaunch huboq_remastered_ver1 huboq_remastered_ver1_teleop.launch'
alias hq0='roslaunch huboq_remastered_ver1 huboq_remastered_ver1_teleop.launch port:=/dev/ttyACM0'
alias hq1='roslaunch huboq_remastered_ver1 huboq_remastered_ver1_teleop.launch port:=/dev/ttyACM1'
alias hq2='roslaunch huboq_remastered_ver1 huboq_remastered_ver1_teleop.launch port:=/dev/ttyACM2'

# Additional useful Alias Commands
alias as='sudo apt-cache search'
alias bh="cat $WS_DIR/bash/bashrc_share"
alias ub='ls -l /dev/serial/by-id/'
alias ui='udevadm info'
alias hi='hwinfo --short'
alias eb='vim bashrc_share'	
alias gs='git config --global user.email \"dongilc@mju.ac.kr\" && git config --global user.name \"dongilc\"'
alias gc='git add . && git commit -m $GIT_NOW && git push $CATKIN_WS_GIT'
alias gb='git add . && git commit -m $GIT_NOW && git push $BASH_GIT'
alias gf='git add . && git commit -m $GIT_NOW && git push $VESC_FW_GIT'
alias am='sudo chmod a+rw /dev/ttyACM0'
alias vd='tio -b 38400 /dev/ttyUSB0'  # VESC Debug using UART2
alias uv='sudo java -jar -Dsun.java2d.uiScale=2.5 ~/Dropbox/DRCL_SHARE/uCCBViewer-2.5.jar'
alias si='nmap -sP 192.168.0.1/24'

# Only in XPS 9570
alias gn='sudo prime-select nvidia'   # Change Prime Graphic Card to nvidia
alias gi='sudo prime-select intel'
